pip install altgraph          
pip install appdirs
pip install argcomplete
pip install cachetools
pip install certifi
pip install charset-normalizer
pip install click
pip install colorama
pip install docx2pdf
pip install google-api-core
pip install google-api-python-client
pip install google-auth
pip install google-auth-httplib2
pip install google-auth-oauthlib
pip install googleapis-common-protos
pip install gspread
pip install httplib2
pip install idna
pip install lxml
pip install numpy
pip install oauth2client
pip install oauthlib
pip install pandas
pip install pefile
pip install Pillow
pip install pip
pip install protobuf
pip install py-machineid
pip install py2exe
pip install pyasn1
pip install pyasn1-modules
pip install pygsheets
pip install pyinstaller
pip install pyinstaller-hooks-
pip install PyMuPDF
pip install PyMuPDFb
pip install pyparsing
pip install PyPDF2
pip install pypng
pip install PyQt5
pip install PyQt5-Qt5
pip install PyQt5-sip
pip install PyQt6
pip install pyqt6-plugins
pip install PyQt6-Qt6
pip install PyQt6-sip
pip install pyqt6-tools
pip install PyQt6-WebEngine
pip install PyQt6-WebEngine-Qt6
pip install PyQtWebEngine
pip install PyQtWebEngine-Qt5
pip install pyserial
pip install python-barcode
pip install python-dateutil
pip install python-docx
pip install python-dotenv
pip install python-escpos
pip install pytz
pip install pyusb
pip install pywin32
pip install pywin32-ctypes
pip install PyYAML
pip install qrcode
pip install qt6-applications
pip install qt6-tools
pip install reportlab
pip install requests
pip install requests-oauthlib
pip install rsa
pip install schedule
pip install setuptools
pip install six
pip install tqdm
pip install typing_extensions
pip install tzdata
pip install uritemplate
pip install urllib3
pip install wheel
pip install winregistry